# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(706, 497)
        Login.setMinimumSize(QtCore.QSize(706, 497))
        Login.setMaximumSize(QtCore.QSize(706, 497))
        Login.setStyleSheet("#centralwidget{\n"
"background-color: rgb(0, 85, 0);\n"
"}\n"
"\n"
"#formLayout{\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"\n"
"\n"
"\n"
"")
        Login.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 290, 611, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(40, 0, 40, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_nombre_usuario = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.label_nombre_usuario.setFont(font)
        self.label_nombre_usuario.setObjectName("label_nombre_usuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nombre_usuario)
        self.text_nombre_usuario = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_nombre_usuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_nombre_usuario.setObjectName("text_nombre_usuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_nombre_usuario)
        self.label_contrasenya = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.label_contrasenya.setFont(font)
        self.label_contrasenya.setObjectName("label_contrasenya")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_contrasenya)
        self.text_contrasenya = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_contrasenya.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_contrasenya.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_contrasenya.setObjectName("text_contrasenya")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_contrasenya)
        self.boton_login = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.boton_login.setFont(font)
        self.boton_login.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_login.setObjectName("boton_login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.boton_login)
        self.label_foto_login = QtWidgets.QLabel(self.centralwidget)
        self.label_foto_login.setEnabled(True)
        self.label_foto_login.setGeometry(QtCore.QRect(93, 90, 521, 71))
        self.label_foto_login.setText("")
        self.label_foto_login.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.label_foto_login.setObjectName("label_foto_login")
        self.boton_registrarse = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.boton_registrarse.setGeometry(QtCore.QRect(360, 380, 261, 30))
        self.boton_registrarse.setMaximumSize(QtCore.QSize(300, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(7, 64, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 28, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 64, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 28, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 64, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 28, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.boton_registrarse.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        self.boton_registrarse.setFont(font)
        icon = QtGui.QIcon.fromTheme("network-receive")
        self.boton_registrarse.setIcon(icon)
        self.boton_registrarse.setIconSize(QtCore.QSize(0, 0))
        self.boton_registrarse.setObjectName("boton_registrarse")
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Guiñote"))
        self.label_nombre_usuario.setText(_translate("Login", "Nombre de usuario:"))
        self.label_contrasenya.setText(_translate("Login", "Contraseña:"))
        self.boton_login.setText(_translate("Login", "Login"))
        self.boton_registrarse.setText(_translate("Login", "¿No tienes cuenta? ¡Registrate gratis!"))
import Imagenes.imagenes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
