# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_buscar_partida.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_buscar_partida(object):
    def setupUi(self, menu_buscar_partida):
        menu_buscar_partida.setObjectName("menu_buscar_partida")
        menu_buscar_partida.resize(706, 497)
        menu_buscar_partida.setMinimumSize(QtCore.QSize(706, 497))
        menu_buscar_partida.setMaximumSize(QtCore.QSize(706, 497))
        self.label = QtWidgets.QLabel(menu_buscar_partida)
        self.label.setGeometry(QtCore.QRect(0, 0, 706, 497))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Imagenes/Tapete_verde.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(menu_buscar_partida)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(10, 100))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_5.setMaximumSize(QtCore.QSize(231, 125))
        self.widget_5.setObjectName("widget_5")
        self.boton_volver = QtWidgets.QPushButton(self.widget_5)
        self.boton_volver.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_volver.setFont(font)
        self.boton_volver.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_volver.setObjectName("boton_volver")
        self.verticalLayout.addWidget(self.widget_5)
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setMaximumSize(QtCore.QSize(231, 360))
        self.widget.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 209, 91))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.boton_buscar_publica = QtWidgets.QPushButton(self.widget)
        self.boton_buscar_publica.setGeometry(QtCore.QRect(30, 110, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_buscar_publica.setFont(font)
        self.boton_buscar_publica.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_buscar_publica.setObjectName("boton_buscar_publica")
        self.verticalLayout.addWidget(self.widget)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(10, 100))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(231, 125))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(231, 360))
        self.widget_2.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"border-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 209, 91))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.boton_crear_privada = QtWidgets.QPushButton(self.widget_2)
        self.boton_crear_privada.setGeometry(QtCore.QRect(30, 100, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_crear_privada.setFont(font)
        self.boton_crear_privada.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_crear_privada.setObjectName("boton_crear_privada")
        self.boton_ingresar_privada = QtWidgets.QPushButton(self.widget_2)
        self.boton_ingresar_privada.setGeometry(QtCore.QRect(60, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_ingresar_privada.setFont(font)
        self.boton_ingresar_privada.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_ingresar_privada.setObjectName("boton_ingresar_privada")
        self.codigo_privada = QtWidgets.QLineEdit(self.widget_2)
        self.codigo_privada.setGeometry(QtCore.QRect(20, 170, 171, 29))
        self.codigo_privada.setText("")
        self.codigo_privada.setObjectName("codigo_privada")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(10, 100))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_4.setMaximumSize(QtCore.QSize(231, 125))
        self.widget_4.setObjectName("widget_4")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 209, 51))
        self.label_3.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.widget_4)
        self.comboBox.setGeometry(QtCore.QRect(10, 50, 191, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_3.setMaximumSize(QtCore.QSize(231, 360))
        self.widget_3.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"border-color: rgb(0, 0, 0);")
        self.widget_3.setObjectName("widget_3")
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 209, 91))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.boton_crear_torneo = QtWidgets.QPushButton(self.widget_3)
        self.boton_crear_torneo.setGeometry(QtCore.QRect(30, 100, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_crear_torneo.setFont(font)
        self.boton_crear_torneo.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_crear_torneo.setObjectName("boton_crear_torneo")
        self.boton_ingresar_torneo = QtWidgets.QPushButton(self.widget_3)
        self.boton_ingresar_torneo.setGeometry(QtCore.QRect(60, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_ingresar_torneo.setFont(font)
        self.boton_ingresar_torneo.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_ingresar_torneo.setObjectName("boton_ingresar_torneo")
        self.codigo_torneo = QtWidgets.QLineEdit(self.widget_3)
        self.codigo_torneo.setGeometry(QtCore.QRect(20, 170, 171, 29))
        self.codigo_torneo.setText("")
        self.codigo_torneo.setObjectName("codigo_torneo")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setMaximumSize(QtCore.QSize(10, 100))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)

        self.retranslateUi(menu_buscar_partida)
        QtCore.QMetaObject.connectSlotsByName(menu_buscar_partida)

    def retranslateUi(self, menu_buscar_partida):
        _translate = QtCore.QCoreApplication.translate
        self.boton_volver.setText(_translate("menu_buscar_partida", "Volver"))
        self.label_6.setText(_translate("menu_buscar_partida", "Partida Pública"))
        self.boton_buscar_publica.setText(_translate("menu_buscar_partida", "Buscar Partida"))
        self.label_2.setText(_translate("menu_buscar_partida", "Jugar"))
        self.label_17.setText(_translate("menu_buscar_partida", "Partida Privada"))
        self.boton_crear_privada.setText(_translate("menu_buscar_partida", "Crear Partida"))
        self.boton_ingresar_privada.setText(_translate("menu_buscar_partida", "Introducir"))
        self.codigo_privada.setPlaceholderText(_translate("menu_buscar_partida", "Introduce código"))
        self.comboBox.setItemText(0, _translate("menu_buscar_partida", "Elige tipo de partida"))
        self.comboBox.setItemText(1, _translate("menu_buscar_partida", "Partida 2 jugadores"))
        self.comboBox.setItemText(2, _translate("menu_buscar_partida", "Partida 3 jugadores"))
        self.comboBox.setItemText(3, _translate("menu_buscar_partida", "Partida 4 jugadores"))
        self.label_18.setText(_translate("menu_buscar_partida", "Torneo"))
        self.boton_crear_torneo.setText(_translate("menu_buscar_partida", "Crear Torneo"))
        self.boton_ingresar_torneo.setText(_translate("menu_buscar_partida", "Introducir"))
        self.codigo_torneo.setPlaceholderText(_translate("menu_buscar_partida", "Introduce código"))
