# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_buscar_partida.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_buscar_partida(object):
    def setupUi(self, menu_buscar_partida):
        menu_buscar_partida.setObjectName("menu_buscar_partida")
        menu_buscar_partida.resize(706, 497)
        menu_buscar_partida.setMinimumSize(QtCore.QSize(706, 497))
        menu_buscar_partida.setMaximumSize(QtCore.QSize(706, 497))
        self.label = QtWidgets.QLabel(menu_buscar_partida)
        self.label.setGeometry(QtCore.QRect(0, 0, 706, 497))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Imagenes/Tapete_verde.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(menu_buscar_partida)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(10, 100))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_5.setMaximumSize(QtCore.QSize(231, 125))
        self.widget_5.setObjectName("widget_5")
        self.boton_volver = QtWidgets.QPushButton(self.widget_5)
        self.boton_volver.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_volver.setFont(font)
        self.boton_volver.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_volver.setObjectName("boton_volver")
        self.verticalLayout.addWidget(self.widget_5)
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setMaximumSize(QtCore.QSize(231, 360))
        self.widget.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 209, 91))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.boton_confirmar_registro = QtWidgets.QPushButton(self.widget)
        self.boton_confirmar_registro.setGeometry(QtCore.QRect(30, 110, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_confirmar_registro.setFont(font)
        self.boton_confirmar_registro.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_confirmar_registro.setObjectName("boton_confirmar_registro")
        self.verticalLayout.addWidget(self.widget)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(10, 100))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(231, 125))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(231, 360))
        self.widget_2.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"border-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 209, 91))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.boton_confirmar_registro_3 = QtWidgets.QPushButton(self.widget_2)
        self.boton_confirmar_registro_3.setGeometry(QtCore.QRect(30, 100, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_confirmar_registro_3.setFont(font)
        self.boton_confirmar_registro_3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_confirmar_registro_3.setObjectName("boton_confirmar_registro_3")
        self.boton_confirmar_registro_4 = QtWidgets.QPushButton(self.widget_2)
        self.boton_confirmar_registro_4.setGeometry(QtCore.QRect(60, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_confirmar_registro_4.setFont(font)
        self.boton_confirmar_registro_4.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_confirmar_registro_4.setObjectName("boton_confirmar_registro_4")
        self.text_nombre_real = QtWidgets.QLineEdit(self.widget_2)
        self.text_nombre_real.setGeometry(QtCore.QRect(20, 170, 171, 29))
        self.text_nombre_real.setObjectName("text_nombre_real")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(10, 100))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_4.setMaximumSize(QtCore.QSize(231, 125))
        self.widget_4.setObjectName("widget_4")
        self.spinBox = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox.setGeometry(QtCore.QRect(10, 50, 191, 30))
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(4)
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 209, 51))
        self.label_3.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.spinBox.raise_()
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_3.setMaximumSize(QtCore.QSize(231, 360))
        self.widget_3.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"border-color: rgb(0, 0, 0);")
        self.widget_3.setObjectName("widget_3")
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 209, 91))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.boton_confirmar_registro_5 = QtWidgets.QPushButton(self.widget_3)
        self.boton_confirmar_registro_5.setGeometry(QtCore.QRect(30, 100, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_confirmar_registro_5.setFont(font)
        self.boton_confirmar_registro_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_confirmar_registro_5.setObjectName("boton_confirmar_registro_5")
        self.boton_confirmar_registro_6 = QtWidgets.QPushButton(self.widget_3)
        self.boton_confirmar_registro_6.setGeometry(QtCore.QRect(60, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_confirmar_registro_6.setFont(font)
        self.boton_confirmar_registro_6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_confirmar_registro_6.setObjectName("boton_confirmar_registro_6")
        self.text_nombre_real_2 = QtWidgets.QLineEdit(self.widget_3)
        self.text_nombre_real_2.setGeometry(QtCore.QRect(20, 170, 171, 29))
        self.text_nombre_real_2.setObjectName("text_nombre_real_2")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setMaximumSize(QtCore.QSize(10, 100))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)

        self.retranslateUi(menu_buscar_partida)
        QtCore.QMetaObject.connectSlotsByName(menu_buscar_partida)

    def retranslateUi(self, menu_buscar_partida):
        _translate = QtCore.QCoreApplication.translate
        self.boton_volver.setText(_translate("menu_buscar_partida", "Volver"))
        self.label_6.setText(_translate("menu_buscar_partida", "Partida Pública"))
        self.boton_confirmar_registro.setText(_translate("menu_buscar_partida", "Buscar Partida"))
        self.label_2.setText(_translate("menu_buscar_partida", "Jugar"))
        self.label_17.setText(_translate("menu_buscar_partida", "Partida Privada"))
        self.boton_confirmar_registro_3.setText(_translate("menu_buscar_partida", "Crear Partida"))
        self.boton_confirmar_registro_4.setText(_translate("menu_buscar_partida", "Introducir"))
        self.text_nombre_real.setText(_translate("menu_buscar_partida", "Introduce código"))
        self.spinBox.setSuffix(_translate("menu_buscar_partida", " jugadores"))
        self.spinBox.setPrefix(_translate("menu_buscar_partida", "Partida "))
        self.label_18.setText(_translate("menu_buscar_partida", "Torneo"))
        self.boton_confirmar_registro_5.setText(_translate("menu_buscar_partida", "Unirse a un torneo"))
        self.boton_confirmar_registro_6.setText(_translate("menu_buscar_partida", "Introducir"))
        self.text_nombre_real_2.setText(_translate("menu_buscar_partida", "Introduce código"))
