# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registro(object):
    def setupUi(self, Registro):
        Registro.setObjectName("Registro")
        Registro.resize(706, 497)
        Registro.setMinimumSize(QtCore.QSize(706, 497))
        Registro.setMaximumSize(QtCore.QSize(706, 497))
        Registro.setStyleSheet("#centralwidget{\n"
"background-color: rgb(0, 85, 0);\n"
"}\n"
"\n"
"#formLayout{\n"
"background-color: rgb(255,255,255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 242, 581, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(40, 0, 40, 0)
        self.formLayout.setSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.label_nombre_real = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.label_nombre_real.setFont(font)
        self.label_nombre_real.setObjectName("label_nombre_real")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nombre_real)
        self.text_nombre_real = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_nombre_real.setObjectName("text_nombre_real")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_nombre_real)
        self.label_nombre_usuario_registro = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.label_nombre_usuario_registro.setFont(font)
        self.label_nombre_usuario_registro.setObjectName("label_nombre_usuario_registro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_nombre_usuario_registro)
        self.text_nombre_usuario_registro = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_nombre_usuario_registro.setObjectName("text_nombre_usuario_registro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_nombre_usuario_registro)
        self.label_correo = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.label_correo.setFont(font)
        self.label_correo.setObjectName("label_correo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_correo)
        self.text_correo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_correo.setObjectName("text_correo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_correo)
        self.boton_terminos = QtWidgets.QCheckBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.boton_terminos.setFont(font)
        self.boton_terminos.setObjectName("boton_terminos")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.boton_terminos)
        self.boton_confirmar_registro = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.boton_confirmar_registro.setFont(font)
        self.boton_confirmar_registro.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.boton_confirmar_registro.setObjectName("boton_confirmar_registro")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.boton_confirmar_registro)
        self.text_contrasenya_registro = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_contrasenya_registro.setObjectName("text_contrasenya_registro")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_contrasenya_registro)
        self.label_contrasenya_registro = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.label_contrasenya_registro.setFont(font)
        self.label_contrasenya_registro.setObjectName("label_contrasenya_registro")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_contrasenya_registro)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 50, 150, 150))
        self.label.setObjectName("label")
        Registro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Registro)
        QtCore.QMetaObject.connectSlotsByName(Registro)

    def retranslateUi(self, Registro):
        _translate = QtCore.QCoreApplication.translate
        Registro.setWindowTitle(_translate("Registro", "Guiñote"))
        self.label_nombre_real.setText(_translate("Registro", "Nombre real:"))
        self.label_nombre_usuario_registro.setText(_translate("Registro", "Nombre de usuario:"))
        self.label_correo.setText(_translate("Registro", "Correo electrónico:"))
        self.boton_terminos.setText(_translate("Registro", "Acepto los términos y condiciones"))
        self.boton_confirmar_registro.setText(_translate("Registro", "Registrarse"))
        self.label_contrasenya_registro.setText(_translate("Registro", "Contraseña:"))
        self.label.setText(_translate("Registro", "<html><head/><body><p><img src=\":/logo/150.png\"/></p></body></html>"))
import Imagenes.imagenes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registro = QtWidgets.QMainWindow()
    ui = Ui_Registro()
    ui.setupUi(Registro)
    Registro.show()
    sys.exit(app.exec_())
